platform :ios, ‘8.0’

target ‘song_RN’ do
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'

    pod 'UMCAnalytics'

    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'

    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'

    # 集成微信(完整版14.4M)
    pod 'UMCShare/Social/WeChat'

    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'

    # 集成QQ/QZone/TIM(完整版7.6M)
    pod 'UMCShare/Social/QQ'

    # 集成新浪微博(精简版1M)
    pod 'UMCShare/Social/ReducedSina'

    # 集成新浪微博(完整版25.3M)
    pod 'UMCShare/Social/Sina'

    # 集成短信
    pod 'UMCShare/Social/SMS'
end